### ISSUE TITLE
[Feature Request] 4K displays...

### ISSUE THREAD

**Issue by ambs** [rednblackgames/HyperLap2D#37] opened 2021-03-21 15:22 UTC
First, thank you so much for taking overlap 2D and giving it a new life. I was really sad of it being dead for some time. I usually use it on my classes, and using a old/dead app wasn't very nice.

My current problem is not properly a bug, but a feature request.
Using OverLap, erm, HyperLap2D in a 4K display is very complicated (using Linux Mint, 0.0.5 of HyperLap).
Is there any way to make it... larger?

Thank you

**Comment by fgnm** [comment] 2021-03-21 16:11
Hi, thank you so much for interesting in the project!
Indeed on some display could be quite unusable.. I've some ideas on how to adjust viewport scale for high resolutions, let me few days for testing it

**Comment by fgnm** [comment] 2021-03-23 20:57
Hey @ambs take a look to latest snapshot [here](https://github.com/rednblackgames/HyperLap2D/actions/runs/680921818), there's a new setting that allow to change UI viewport density. It may not looks sharp when upscale UI, but at moment this is the best result I can achieve, let me know how it looks.

**Comment by ambs** [comment] 2021-03-23 21:11
Hi. Testing on my laptop (also 4K display), running Linux, my X11 goes of the peak using 100% cpu, and system gets unusable.
I have no idea if that is a result of your change, or if this is a specific problem on my laptop.

Tomorrow I will test on the original machine and let you know.
Thanks

**Comment by fgnm** [comment] 2021-03-23 21:30
Uhm that's sounds bad, it might be related to recent switch on OpenGL 3.2... Please can you try this other [snapshot](https://github.com/rednblackgames/HyperLap2D/actions/runs/668186750)? It's the latest one before new GL version

**Comment by ambs** [comment] 2021-03-23 21:37
With that version I get the 110% CPU for the HyperLap binary (not the X11).
Also, tried to find the option for bigger UI, but without luck.
Thanks

**Comment by fgnm** [comment] 2021-03-23 21:51
Sorry if I ask, may you try this other [snapshot](https://github.com/rednblackgames/HyperLap2D/actions/runs/603444825)? 😄 I'd like to identify high CPU reason becasue itn't really normal..

Regarding scale UI option it's here (of course this is available only in the latest snapshot), it's a slider, less density means big UI:
![image](https://user-images.githubusercontent.com/5543339/112223369-1c862300-8c2a-11eb-8a3e-062c46188715.png)

**Comment by ambs** [comment] 2021-03-23 21:55
Unfortunately I do not have big news. Still high CPU usage. Give me a minute to test the latest "stable" version.

**Comment by ambs** [comment] 2021-03-23 21:59
OK, 0.0.5 is not running properly on my laptop (high cpu usage).
For reference, I am running Linux Mint, using nvidia geforce directly on X11.
I am happy to help debugging, f you give more details on how to do that.
Cheers

**Comment by fgnm** [comment] 2021-03-23 22:10
Thanks for the info, I usually work on Ubuntu using X11 + Radeon driver without issues.. Since any configuration of vSync and thread sync doesn't work properly on your machine all can I imagine now is a driver issue, that may be related to libGDX itself.. I'll try to find a machine where to reproduce this bug, meanwhile would be very helpful a report from a profiler while running hyperlap.. Have you ever worked with VisualVM?

**Comment by ambs** [comment] 2021-03-24 16:51
Hi. Didn't notice the Discord server. Will do it as soon as I can.
No, never used VisualVM.
Tried 0.0.5 on my tower, and hyperlap works without cpu issues.

**Comment by fgnm** [comment] 2021-03-24 19:11
With VisualVM you should be able to see which part of the code is consuming so much on the laptop CPU.. You may try to use it and see what's going on. I think you'll need to run hyperlap from source. Unfortunately I'm not able to reproduce the issue.

**Comment by ambs** [comment] 2021-03-24 20:19
during the weekend will try to understand what might be going on. During the week is hard to get some time...

**Comment by ambs** [comment] 2021-03-24 20:44
Was testing running the binary, and see its output. I do not think this is relevant, but I'm sharing anyway:

```
Loading Proxies...
Loading Views...
HyperLap2D 0.0.5
Linux [5.4.0-67-generic - amd64]
NVIDIA Corporation GeForce GTX 960M/PCIe/SSE2
Screen size 3840 x 2160
GL version 4.6.0 NVIDIA 450.102.04
Shaders version 4.60 NVIDIA
Loading Commands...
Loading Plugins...
Plugins directory: /opt/hyperlap2d/lib/app/plugins
Plugins loaded: 4
Plugins directory: /home/ambs/.hyperlap2d/plugins
Plugins loaded: 0
Plugins directory: /opt/hyperlap2d/bin/plugins
Plugins loaded: 0
Initializing...
[GLProfiler] Error GL_INVALID_ENUM from glClearColor
Content-Type = application/json; charset=utf-8
Content-Disposition = null
Content-Length = 5878
```

**Comment by ambs** [comment] 2021-03-24 21:03
As a sidenode, built from GIT, and the zoom is working :-)

**Comment by fgnm** [comment] 2021-03-26 18:50
I close this one, as original topic is fixed ;)

**Closed by fgnm** 2021-03-26 18:50 UTC
Labels: bug, enhancement
